from constant.value_infos import enum_value_type
import json


def parse_entrance(json_text: str):
    value_type = json.loads(json_text)["type"]
    match value_type:
        case enum_value_type.ENUM_EVENT:
            ...
        case enum_value_type.ENUM_GLOBALMAP:
            ...
        case enum_value_type.ENUM_ITEM:
            ...
        case enum_value_type.ENUM_LOCALMAP:
            ...
        case enum_value_type.ENUM_ROLEHERO:
            ...
        case enum_value_type.ENUM_ROLEMOB:
            ...
        case enum_value_type.ENUM_SKILL:
            ...
